language: cpp
dist: trusty
sudo: required
compiler:
    - gcc
os:
    - linux
before_install:
    - wget -O - https://rofi.roger-ferrer.org/apt/mirror/apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo add-apt-repository -s 'deb [arch=amd64] https://rofi.roger-ferrer.org/apt/mirror/apt.llvm.org/trusty llvm-toolchain-trusty-4.0 main'
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y gcc-6 g++-6 gfortran-6 flex bison gperf libsqlite3-dev clang-4.0 llvm-4.0-dev
    - ./scripts/install-nanox.sh
script:
    - "autoreconf -fiv &&
    ./configure CC=gcc-6 CXX=g++-6 GFORTRAN=gfortran-6 FC=gfortran-6 CFLAGS=\"-O0\" CXXFLAGS=\"-O0\" LLVM_CONFIG=\"/usr/bin/llvm-config-4.0\" --prefix=$HOME/mcxx-install --enable-fortran-llvm-codegen --enable-ompss --with-nanox=$HOME/nanox-install &&
    make -j$(nproc) &&
    make install &&
    make check"
    - "grep -C20 'failed!' tests/test.log || true"
