language: cpp
dist: trusty
sudo: required
compiler:
    - gcc
os:
    - linux
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y flex bison gperf gfortran libsqlite3-dev
script:
    - "autoreconf -fiv &&
    ./configure CFLAGS=\"-O0\" CXXFLAGS=\"-O0\" --prefix=$HOME/mcxx-install &&
    make -j$(nproc) &&
    make install &&
    make check"
    - "grep -C20 'failed!' tests/test.log || true"
