language: cpp
dist: trusty
sudo: required
compiler:
    - gcc
os:
    - linux
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y flex bison gperf gfortran libsqlite3-dev
script:
    ./configure --prefix=$HOME/mcxx-install && make && make install && make check
